### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by undercase** [GreenVars/diary#1]
I think there should be a guide for those who would like to contribute to the library - it would help increase adoption.

**Comment by GreenVars** [comment]
Certainly a good idea, first question is what could people contribute? Maybe some formats and levels and different database configs. A contribution guide would probably consist of 
1. clone the repo
2. read the source
3. run the tests
4. code your changes
5. write tests for the changes
6. write the PR

**Comment by undercase** [comment]
That's a good start. It should also include the commands for each task. I'm not sure what people would contribute, but I think a good start is including some quick-setup commands that set up logging and connect it to a database for sqlite, postgres, and mysql.

**Comment by undercase** [comment]
I'll submit a pull request with that guide formatted in markdown w/ commands.
